project_id = "nweklcxzoemcnwaoakvq"

[functions.verify-admin-email]
verify_jwt = false

[functions.submit-form]
verify_jwt = false

[functions.start-checkout]
verify_jwt = false

[functions.submit-job-application]
verify_jwt = false

[functions.ghl-admin-fields]
verify_jwt = true
